### ISSUE TITLE
Create documentation as it's in VJS and Element

### ISSUE THREAD

**Issue by nikoloza** [vigour-io/scratch#3]
I think using this: https://github.com/Paratron/CSSdoc

**Comment by jimdebeer** [comment]
shawn is creating the solution for this check vigour-util for this

**Comment by shawninder** [comment]
@nikoloza I'm not sure I'm the best person to document `scratch`. I've never used it, never seen the code, anything... I will have a nice example of how we would like documentation to be done soon. For now, I think vigour-util is the best example, but it will be better when I finish making the documentation tooling I'm working on (automated badges, jsdoc stuff, nightmare testing for the browser, etc)

**Comment by nikoloza** [comment]
Ah no Shawn, I already have most of docs here. We just need tool to generate one

**Comment by nikoloza** [comment]
Docs example here, exactly like in jsdoc https://github.com/vigour-io/scratch/blob/develop/lib/mixins/misc.less

**Comment by jimdebeer** [comment]
I meant shawn made a good doc for util --> check it

**Comment by jimdebeer** [comment]
not let shawn make it

**Comment by nikoloza** [comment]
I thought hes working on tool that makes docs

**Comment by shawninder** [comment]
yeah I'm working on it. Don't worry I will tell everyone when I'm done! I'm expecting to have at least the jsdoc stuff done by this weekend :)

By the way, you're using jsdoc in a less file... This is a use case I hadn't thought of. I will make an issue for this for myself because I think it's nice and I don't think there is any cssdoc or lessdoc or anything...

Also worth noting we're going to be moving to SCSS (or maybe even CSS4 directly if we find some transpilers). I will just make sure my stuff supports jsdoc-style comments in scss and less files as well as js

**Comment by nikoloza** [comment]
@shawninder thanks man. you can find out the way you prefer, so I can always change docs to make them fit for your tools

**Comment by shawninder** [comment]
@nikoloza I'm also super open to ideas and request if you think I can make a little tool to help you do your documentation work.

**Comment by nikoloza** [comment]
Awesome man, thanks :)
